/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PetCareUI;

import SupplierUI.SupplierWorkArea;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import onlinepetstore.Clothing;
import onlinepetstore.OnlineStore;
import onlinepetstore.PetCare;
import onlinepetstore.PetCareAppointment;
import onlinepetstore.Pricing;
import onlinepetstore.PricingDirectory;
import ui.MainJFrame;

/**
 *
 * @author moukthikamanapati
 */
public class PricesUpload extends javax.swing.JPanel {

    /**
     * Creates new form PricesUpload
     */
//    public PricesUpload() {
//        initComponents();
//    }
JPanel userprocess;
PricingDirectory pricingDirectory;
    private OnlineStore os;
    private PetCareAppointment psapp;
    public PricesUpload(JPanel userprocess, PricingDirectory pricingDirectory) {
        initComponents();
        this.userprocess = userprocess;
        this.pricingDirectory = pricingDirectory;
    }

    public PricesUpload(JPanel userprocess, OnlineStore os) {
        
    initComponents();
        this.userprocess = userprocess;
        this.os = os;
        pricingDirectory = os.getPricingDirectory();
        this.psapp = os.getPapp();
       populateTable();
       populateServices();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnPricing = new javax.swing.JButton();
        TxtServiceName = new javax.swing.JTextField();
        TxtCategory = new javax.swing.JTextField();
        TxtPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        papp = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        service = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(123, 69, 12));

        BtnPricing.setBackground(new java.awt.Color(255, 255, 204));
        BtnPricing.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        BtnPricing.setText("Upload");
        BtnPricing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPricingActionPerformed(evt);
            }
        });

        TxtServiceName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        TxtCategory.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        TxtCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCategoryActionPerformed(evt);
            }
        });

        TxtPrice.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Service");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Cate");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("Price");

        BtnBack.setBackground(new java.awt.Color(255, 255, 204));
        BtnBack.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        BtnBack.setText("BACK");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        papp.setBackground(new java.awt.Color(219, 210, 196));
        papp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "pet name", "service name", "price"
            }
        ));
        papp.setRowHeight(24);
        jScrollPane2.setViewportView(papp);

        service.setBackground(new java.awt.Color(219, 210, 196));
        service.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "service name", "category", "price"
            }
        ));
        service.setRowHeight(24);
        jScrollPane3.setViewportView(service);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtServiceName, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(TxtCategory)
                            .addComponent(TxtPrice)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(BtnPricing))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnBack)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(BtnPricing)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPricingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPricingActionPerformed
        String service = String.valueOf(TxtServiceName.getText());
        double price = Double.parseDouble(TxtPrice.getText());
        String cat = String.valueOf(TxtCategory.getText());
        Pricing pricing = pricingDirectory.addPricing();
        pricing.setServicetype(service);
        pricing.setPrice(price);
        pricing.setCategory(cat);
         populateTable();
       populateServices();
        JOptionPane.showMessageDialog(null, "Pricing Details added!", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BtnPricingActionPerformed

    private void TxtCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCategoryActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
     os.setPricingDirectory(pricingDirectory);
        new MainJFrame(os).setVisible(true);    
    }//GEN-LAST:event_BtnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnPricing;
    private javax.swing.JTextField TxtCategory;
    private javax.swing.JTextField TxtPrice;
    private javax.swing.JTextField TxtServiceName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable papp;
    private javax.swing.JTable service;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
       DefaultTableModel model = (DefaultTableModel) papp.getModel();
        model.setRowCount(0);
        System.out.println("populate on pet type");
        
        for (PetCare p : psapp.getAppointmentList()) {
//           if(p.getUsername().equals(user.getUsername().toString())){
            Object row[] = new Object[3];
            row[0] = p;
            row[2] = p.getService().getPrice();
            row[1] = p.getService().getServicename();
        
            model.addRow(row);  
       
    
    
//   }
        }  }

    private void populateServices() {
         DefaultTableModel model = (DefaultTableModel) service.getModel();
        model.setRowCount(0);
       // System.out.println("pp+"+pricingDirectory.getPriceList().size());
        for (Pricing p : pricingDirectory.getPriceList()) {
            
                Object row[] = new Object[3];
                row[0] = p;
                row[1] = p.getServicetype();
                row[2] = p.getPrice();
                model.addRow(row);
            }
        } 
}
