/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Adoption;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import onlinepetstore.Adoption;
import onlinepetstore.AdoptionList;
import onlinepetstore.Doctor;
import onlinepetstore.MyPetsList;
import onlinepetstore.OnlineStore;
import onlinepetstore.Pet;
import onlinepetstore.PetDirectory;
import onlinepetstore.User;

/**
 *
 * @author moukthikamanapati
 */
public class AdoptionRequest extends javax.swing.JPanel {

    /**
     * Creates new form AdoptionRequest
     */
    JPanel userProcess;
    User user;
    PetDirectory petDirectory;
    AdoptionList adl;
    private OnlineStore os;
    private MyPetsList mypets;

    public AdoptionRequest(JPanel userProcess, PetDirectory petDirectory, User user, AdoptionList adl) {
        initComponents();
        this.userProcess = userProcess;
        this.user = user;
        this.petDirectory = petDirectory;
        this.adl = adl;
        populateTable();
    }

    AdoptionRequest(JPanel userProcess, OnlineStore os, User user) {
        initComponents();
     this.userProcess = userProcess;
     this.os = os;
     this.user = user;
     this.adl = os.getAdl();
     this.petDirectory = os.getPetDirectory();
     this.mypets = os.getMypetList();
     this.petDirectory = os.getPetDirectory();
     populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtincome = new javax.swing.JTextField();
        txtduration = new javax.swing.JTextField();
        txtreason = new javax.swing.JTextField();
        reg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpet = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();

        setBackground(new java.awt.Color(123, 69, 12));

        txtincome.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        txtduration.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        txtreason.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        reg.setBackground(new java.awt.Color(255, 255, 204));
        reg.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        reg.setText("Register");
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("income");

        tblpet.setBackground(new java.awt.Color(219, 210, 196));
        tblpet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "PetNAme", "Age", "Breed"
            }
        ));
        tblpet.setRowHeight(24);
        jScrollPane1.setViewportView(tblpet);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setText("duration");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel3.setText("reason");

        btnback.setBackground(new java.awt.Color(255, 255, 204));
        btnback.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnback)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtincome, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtduration, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtreason, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(reg, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnback)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtincome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtduration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(txtreason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addComponent(reg, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
          if(adl==null)
        {
            adl = new AdoptionList();
        }
        Adoption app = adl.addAdoption();
          int row = tblpet.getSelectedRow();
       if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int dur;
        double inc;
        try{
         dur = Integer.parseInt(txtduration.getText());
        
         inc = Double.parseDouble(txtincome.getText());
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please check if you have entered all the values", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String reason = String.valueOf(txtreason.getText());
           if (reason.equals("") ) {
            JOptionPane.showMessageDialog(this, "Please check if you have entered all the values", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Pet pet = (Pet) tblpet.getValueAt(row, 0);
        Pet n = pet;
        app.setPet(n);
        app.setIncome(inc);
        app.setDuration(dur);
        app.setUser(user);
        app.setStatus("open");
        os.setPetDirectory(petDirectory);
        JOptionPane.showMessageDialog(null, "Register to adopt that pet !", "Info", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_regActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
         os.setAdl(adl);
         //System.out.println(adl.getAdoptionList());
        AdoptionWorkArea add = new AdoptionWorkArea(userProcess,os  ,user );
        userProcess.add("AdoptionWorkArea", add);
        CardLayout layout = (CardLayout) userProcess.getLayout();
        layout.next(userProcess);
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reg;
    private javax.swing.JTable tblpet;
    private javax.swing.JTextField txtduration;
    private javax.swing.JTextField txtincome;
    private javax.swing.JTextField txtreason;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
       
     DefaultTableModel model = (DefaultTableModel) tblpet.getModel();
        model.setRowCount(0);
        System.out.println("populate on adopt table");
        //  System.out.println(p.getHouse().getCommunity().getCity().getCityName());
        for (Pet p : petDirectory.getPetlist()) {
           if(p.getPetType().equalsIgnoreCase("Adoption"))
           {
            Object row[] = new Object[3];
            row[0] = p;
            row[1] = p.getAge();
            row[2] = p.getBreed();
          

            model.addRow(row);
    }
        }
    
    }
}
