/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Admin;

import java.awt.CardLayout;
import javax.swing.JPanel;
import onlinepetstore.OnlineStore;

/**
 *
 * @author moukthikamanapati
 */
public class AdminPage extends javax.swing.JPanel {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        
    }
JPanel userprocess;
OnlineStore os;
    public AdminPage(JPanel userprocess, OnlineStore os) {
       initComponents();
       this.userprocess = userprocess;
               this.os = os;
               }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Users = new javax.swing.JButton();
        Roles = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(123, 69, 12));

        Users.setBackground(new java.awt.Color(255, 255, 204));
        Users.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        Users.setText("Users Directory");
        Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersActionPerformed(evt);
            }
        });

        Roles.setBackground(new java.awt.Color(255, 255, 204));
        Roles.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        Roles.setText("Create Roles");
        Roles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RolesActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jButton3.setText("LogOut");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Users, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Roles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Users, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(Roles, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersActionPerformed
      UsersDirectory us = new UsersDirectory(userprocess, os);
            userprocess.add("UsersDirectory", us);
            CardLayout layout = (CardLayout) userprocess.getLayout();
            layout.next(userprocess);
    }//GEN-LAST:event_UsersActionPerformed

    private void RolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RolesActionPerformed
       CreateRoles ap = new CreateRoles(userprocess, os);
            userprocess.add("CreateRoles", ap);
            CardLayout layout = (CardLayout) userprocess.getLayout();
            layout.next(userprocess);
    }//GEN-LAST:event_RolesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Roles;
    private javax.swing.JButton Users;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
