/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SupplierUI;

import java.awt.CardLayout;
import javax.swing.JPanel;
import onlinepetstore.OnlineStore;
import onlinepetstore.Pet;
import onlinepetstore.PetDirectory;

/**
 *
 * @author moukthikamanapati
 */
public class UpdatePet extends javax.swing.JPanel {

    /**
     * Creates new form UpdatePet
     */
//    public UpdatePet() {
//        initComponents();
//    }
    JPanel userProcess;
    PetDirectory petDirectory;
    Pet pet;
    private OnlineStore os;

//    UpdatePet(JPanel userProcess, PetDirectory petDirectory, Pet pet) {
//        initComponents();
//        this.userProcess = userProcess;
//        this.petDirectory = petDirectory;
//        this.pet = pet;
//        populateCombo();
//    }

    UpdatePet(JPanel userProcess, OnlineStore os, Pet pet) {
     initComponents();
        this.userProcess = userProcess;
        this.petDirectory = os.getPetDirectory();
        this.pet = pet;
        this.os = os;
        populateCombo();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        cmbpet = new javax.swing.JComboBox<>();
        txtval = new javax.swing.JTextField();
        update = new javax.swing.JButton();

        setBackground(new java.awt.Color(123, 69, 12));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbpet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtval.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        update.setBackground(new java.awt.Color(255, 255, 204));
        update.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(cmbpet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtval, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbpet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(update))
                .addContainerGap(197, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String filtername = (String) cmbpet.getSelectedItem();
        String filtervalue = String.valueOf(txtval.getText());
        if (filtername.equals("pet name")) {
            pet.setPetName(filtervalue);
        } else if (filtername.equals("Type")) {
            pet.setPetType(filtervalue);
        } else if (filtername.equals("breed")) {
            pet.setBreed(filtervalue);
        } else if (filtername.equals("sex")) {
            pet.setSex(filtervalue);
        } else if (filtername.equals("age")) {
            pet.setAge(Integer.parseInt(txtval.getText()));
        } else if (filtername.equals("price")) {
            pet.setPrice(Double.parseDouble(txtval.getText()));
        }

    }//GEN-LAST:event_updateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      os.setPetDirectory(petDirectory);
        EditPet ep = new EditPet(userProcess, os);
        userProcess.add("EditPet", ep);
        CardLayout layout = (CardLayout) userProcess.getLayout();
        layout.next(userProcess);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbpet;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField txtval;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private void populateCombo() {
        cmbpet.removeAllItems();

        cmbpet.addItem("pet name");
        cmbpet.addItem("age");
        cmbpet.addItem("Type");
        cmbpet.addItem("price");
        cmbpet.addItem("breed");
        cmbpet.addItem("sex");
    }
}
