/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PetCareUI;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import onlinepetstore.MyPets;
import onlinepetstore.MyPetsList;
import onlinepetstore.OnlineStore;
import onlinepetstore.PetCare;
import onlinepetstore.PetCareAppointment;
import onlinepetstore.User;

/**
 *
 * @author moukthikamanapati
 */
public class PetAppointmentView extends javax.swing.JPanel {

    private JPanel service;
    private User user;
    private OnlineStore os;
    private PetCareAppointment psapp;
    private MyPetsList mypetslist;

    /**
     * Creates new form PetAppointmentView
     */
    public PetAppointmentView() {
        initComponents();
    }

    public PetAppointmentView(JPanel service, OnlineStore os, User user) {
        initComponents();
        this.service = service;
        this.os = os;

        this.user = user;
        this.psapp = os.getPapp();
        this.mypetslist = os.getMypetList();
        os.setMypetList(mypetslist);
        os.setPapp(psapp);
System.out.print(user.getUsername());
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        papp = new javax.swing.JTable();
        cancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(123, 69, 12));

        papp.setBackground(new java.awt.Color(219, 210, 196));
        papp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "My Pet", "Service Name", "Price"
            }
        ));
        papp.setRowHeight(24);
        jScrollPane1.setViewportView(papp);

        cancel.setBackground(new java.awt.Color(255, 255, 204));
        cancel.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cancel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        int row = papp.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        PetCare p = (PetCare) papp.getValueAt(row, 0);
        psapp.removePetCare(p);
        populateTable();
    }//GEN-LAST:event_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable papp;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {

        DefaultTableModel model = (DefaultTableModel) papp.getModel();
        model.setRowCount(0);
        System.out.println("populate on pet type");

        for (PetCare p : psapp.getAppointmentList()) {
           if(p.getUsername().equals(user.getUsername().toString())){
            Object row[] = new Object[3];
            row[0] = p;
            row[2] = p.getService().getPrice();
            row[1] = p.getService().getServicename();

            model.addRow(row);

   }
        }
    }
}
