/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserUI;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import onlinepetstore.MasterOderList;
import onlinepetstore.OnlineStore;
import onlinepetstore.Order;
import onlinepetstore.OrderItemMerch;
import onlinepetstore.OrderItemPet;
import onlinepetstore.User;

/**
 *
 * @author moukthikamanapati
 */
public class OrderHistory extends javax.swing.JPanel {

    private MasterOderList masterList;
    private OnlineStore os;
    private User user;

    /**
     * Creates new form OrderHistory
     */
//    public OrderHistory() {
//       
//    }

    OrderHistory(JPanel userProcess, OnlineStore os, User user) {
        initComponents(); 
        this.user = user;
        this.os = os;
        masterList = os.getMasterList();
       
        populateTable();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderpet = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(123, 69, 12));

        orderpet.setBackground(new java.awt.Color(219, 210, 196));
        orderpet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        orderpet.setRowHeight(18);
        jScrollPane1.setViewportView(orderpet);

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jButton1.setText("BACK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderpet;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
       
        DefaultTableModel model = (DefaultTableModel) orderpet.getModel();
        model.setRowCount(0);

        for (Order o : os.getMasterList()   .getOrderlist()) {
            Object row[] = new Object[2];
            for(OrderItemPet op : o.getOderitem()){
                if(op.getUsername().equalsIgnoreCase(user.getUsername())){
            row[0] = op.getPet().getPetName();
            row[1] = op.getPet().getPrice();
                }
            }
            model.addRow(row);
        }

    
    
    }
}
