/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Adoption;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import onlinepetstore.Adoption;
import onlinepetstore.AdoptionList;
import onlinepetstore.OnlineStore;
import onlinepetstore.Pet;
import onlinepetstore.PetDirectory;
import onlinepetstore.User;

/**
 *
 * @author moukthikamanapati
 */
public class AdoptionStatus extends javax.swing.JPanel {

    JPanel userProcess;
    User user;
    PetDirectory petDirectory;
    AdoptionList adl;
    private OnlineStore os;

    AdoptionStatus(JPanel userProcess, PetDirectory petDirectory, User user, AdoptionList adl) {
        initComponents();
        this.userProcess = userProcess;
        this.user = user;
        this.petDirectory = petDirectory;
        this.adl = adl;
        populateTable();

    }

    AdoptionStatus(JPanel userProcess, OnlineStore os, User user) {
      initComponents();
     this.userProcess = userProcess;
     this.os = os;
     this.user = user;
     this.adl = os.getAdl();
     this.petDirectory = os.getPetDirectory();
     populateTable();
    }

    /**
     * Creates new form AdoptionStatus
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        adoptionstatus = new javax.swing.JTable();
        Btnback = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(123, 69, 12));

        adoptionstatus.setBackground(new java.awt.Color(219, 210, 196));
        adoptionstatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PetName", "sex", "type", "status"
            }
        ));
        adoptionstatus.setRowHeight(24);
        jScrollPane1.setViewportView(adoptionstatus);

        Btnback.setBackground(new java.awt.Color(255, 255, 204));
        Btnback.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        Btnback.setText("Back");
        Btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnbackActionPerformed(evt);
            }
        });

        cancel.setBackground(new java.awt.Color(255, 255, 204));
        cancel.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        cancel.setText("cancel appt");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(cancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnbackActionPerformed
        os.setAdl(adl);
        AdoptionWorkArea add = new AdoptionWorkArea(userProcess, os,user );
        userProcess.add("AdoptionWorkArea", add);
        CardLayout layout = (CardLayout) userProcess.getLayout();
        layout.next(userProcess);
    }//GEN-LAST:event_BtnbackActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        int row = adoptionstatus.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        onlinepetstore.Adoption p = (onlinepetstore.Adoption) adoptionstatus.getValueAt(row, 0);
        adl.removeAdoption(p);
        populateTable();
        JOptionPane.showMessageDialog(this, "Cancelled apointment", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnback;
    private javax.swing.JTable adoptionstatus;
    private javax.swing.JButton cancel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
    
     DefaultTableModel model = (DefaultTableModel) adoptionstatus.getModel();
        model.setRowCount(0);
        System.out.println("populate on adoption table");
        System.out.println("adl" + adl );
        for (Adoption ad : adl.getAdoptionList()) {
           if(ad.getUser().getUsername().equals(user.getUsername())){
            Object row[] = new Object[4];
            row[0] = ad;
            row[1] = ad.getPet().getSex();
            if(ad.getDuration()==0){
            row[2] = "adoption";
                    }
            else
            {
                row[2] = "Foster Care";
            }
            row[3] = ad.getStatus();

            model.addRow(row);
    
        }
        }
    
    }
}
