/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserUI;

import java.awt.CardLayout;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import javax.swing.JPanel;
import onlinepetstore.AdoptionList;
import onlinepetstore.AppointmentDirectory;
import onlinepetstore.ClothingDirectory;
import onlinepetstore.DoctorList;
import onlinepetstore.OnlineStore;
import onlinepetstore.Order;
import onlinepetstore.Pet;
import onlinepetstore.PetDirectory;
import onlinepetstore.PricingDirectory;
import onlinepetstore.User;
import onlinepetstore.UserDirectory;

/**
 *
 * @author moukthikamanapati
 */
public class SpecificPet extends javax.swing.JPanel {

    /**
     * Creates new form SpecificPet
     */
      JPanel userProcess;
    PetDirectory petDirectory;
    Order currentorder;
    Pet pet;
    ClothingDirectory clothingDirectory;
    PricingDirectory pricingDirectory;
    UserDirectory userDirectory;
    User user;
     DoctorList doclist;
     AppointmentDirectory apphis;
      AdoptionList adl;
       OnlineStore os;
//    public SpecificPet(JPanel userProcess, PetDirectory petDirectory, Pet pet, Order currentorder,ClothingDirectory clothingDirectory,PricingDirectory pricingDirectory,UserDirectory userDirectory,User user, DoctorList doclist,AppointmentDirectory apphis, AdoptionList adl) {
//        initComponents();
//        this.userProcess = userProcess;
//        this.petDirectory = petDirectory;
//        this.pet = pet;
//        this.user = user;
//        this.currentorder = currentorder;
//        this.clothingDirectory = clothingDirectory;
//        this.pricingDirectory= pricingDirectory;
//        this.userDirectory= userDirectory;
//        this.doclist = doclist;
//        this.apphis = apphis;
//        labelimage.setIcon(pet.getImage());
//        TxtPetName.setText(pet.getPetName());
//        TxtPrice.setText(String.valueOf(pet.getPrize()));
//        TxtSex.setText(pet.getSex());
//        TxtAge.setText(String.valueOf(pet.getAge()));
//    }

public static BufferedImage scaleImage(int w, int h, BufferedImage img) throws Exception {
        BufferedImage bufferimg;
        bufferimg = new BufferedImage(w, h, BufferedImage.TRANSLUCENT);
        Graphics2D graphic = (Graphics2D) bufferimg.createGraphics();
        graphic.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        graphic.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        graphic.drawImage(img, 0, 0, w, h, null);
        graphic.dispose();
        return bufferimg;
    }
public SpecificPet(JPanel userProcess, PetDirectory petDirectory, Pet pet, Order currentorder, ClothingDirectory clothingDirectory, PricingDirectory pricingDirectory, UserDirectory userDirectory, User user, DoctorList doclist, AppointmentDirectory apphis, AdoptionList adl) {
        initComponents();
        this.userProcess = userProcess;
        this.petDirectory = petDirectory;
        this.pet = pet;
        this.user = user;
        this.currentorder = currentorder;
        this.clothingDirectory = clothingDirectory;
        this.pricingDirectory = pricingDirectory;
        this.userDirectory = userDirectory;
        this.doclist = doclist;
        this.apphis = apphis;
//        labelimage.se
        labelimage.setIcon(pet.getImage());
        TxtPetName.setText(pet.getPetName());
        TxtPrice.setText(String.valueOf(pet.getPrice()));
        TxtSex.setText(pet.getSex());
        TxtAge.setText(String.valueOf(pet.getAge()));
    }

    SpecificPet(JPanel userProcess, OnlineStore os, Pet pet) {
       initComponents();
        this.userProcess = userProcess;
        this.os = os;
        this.petDirectory = os.getPetDirectory();
       // this.pet = pet;
        labelimage.setIcon(pet.getImage());
        TxtPetName.setText(pet.getPetName());
        TxtPrice.setText(String.valueOf(pet.getPrice()));
        TxtSex.setText(pet.getSex());
        TxtAge.setText(String.valueOf(pet.getAge()));
        txtbreed.setText(pet.getBreed());
        txtlife.setText(String.valueOf(pet.getLifeExp()));
    }
    public static Image copyScale(Pet p) {
        // labelimage.setIcon(new ImageIcon(SpecificPet.copyScale(pet)));
        return p.getImage().getImage().getScaledInstance(250, 250, Image.SCALE_DEFAULT);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelimage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TxtPetName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtSex = new javax.swing.JTextField();
        TxtAge = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtlife = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtbreed = new javax.swing.JTextField();

        setBackground(new java.awt.Color(123, 69, 12));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("VIEW PET");

        BtnBack.setBackground(new java.awt.Color(255, 255, 204));
        BtnBack.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        BtnBack.setText("BACK");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        TxtPetName.setFont(new java.awt.Font("Noto Sans Myanmar", 0, 18)); // NOI18N
        TxtPetName.setBorder(null);
        TxtPetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPetNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("Price:");

        TxtPrice.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        TxtPrice.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Sex:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setText("Age:");

        TxtSex.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        TxtSex.setBorder(null);

        TxtAge.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        TxtAge.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setText("Life exp :");

        txtlife.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtlife.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setText("Breed:");

        txtbreed.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtbreed.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtbreed))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TxtPetName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                                .addComponent(TxtSex, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtPrice, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(TxtAge)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtlife, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)))
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtSex, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtlife, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtbreed, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(labelimage)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(214, 214, 214)
                .addComponent(BtnBack)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelimage)
                .addGap(56, 56, 56)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
         
        ViewPet vw = new ViewPet(userProcess,os,user);
        userProcess.add("ViewPet", vw);
        CardLayout layout = (CardLayout) userProcess.getLayout();
        layout.next(userProcess);
    }//GEN-LAST:event_BtnBackActionPerformed

    private void TxtPetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPetNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JTextField TxtAge;
    private javax.swing.JTextField TxtPetName;
    private javax.swing.JTextField TxtPrice;
    private javax.swing.JTextField TxtSex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelimage;
    private javax.swing.JTextField txtbreed;
    private javax.swing.JTextField txtlife;
    // End of variables declaration//GEN-END:variables
}
