/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserUI;

import Adoption.AdoptionWorkArea;
import java.awt.CardLayout;
import javax.swing.JPanel;
import onlinepetstore.AdoptionList;
import onlinepetstore.AppointmentDirectory;
import onlinepetstore.ClothingDirectory;
import onlinepetstore.DoctorList;
import onlinepetstore.FoodList;
import onlinepetstore.MedicineList;
import onlinepetstore.MerchOrderList;
import onlinepetstore.OnlineStore;
import onlinepetstore.Order;
import onlinepetstore.Pet;
import onlinepetstore.PetCareAppointment;
import onlinepetstore.PetDirectory;
import onlinepetstore.PricingDirectory;
import onlinepetstore.User;
import onlinepetstore.UserDirectory;
import ui.MainJFrame;
import veternary.Appointment;

/**
 *
 * @author moukthikamanapati
 */
public class UserWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form UserWorkArea
     */
    JPanel userProcess;

    OnlineStore os;
//    public UserWorkArea(JPanel userProcess, PetDirectory petDirectory, Order currentorder, ClothingDirectory clothingDirectory, PricingDirectory pricingDirectory, UserDirectory userDirectory, User user, DoctorList doclist,AppointmentDirectory apphis, AdoptionList adl,  FoodList foodList,MedicineList medList,MerchOrderList merchList,PetCareAppointment papp) {
//        initComponents();
//        this.userProcess = userProcess;
//        this.petDirectory = petDirectory;
//        this.currentorder = currentorder;
//        this.clothingDirectory = clothingDirectory;
//        this.pricingDirectory = pricingDirectory;
//        this.userDirectory = userDirectory;
//        this.doclist = doclist;
//        this.foodList = foodList;
//        this.medList = medList;
//        this.user = user;
//        this.apphis = apphis;
//        this.adl = adl;
//        this.merchList = merchList;
//        this.papp = papp;
//    }
    User user;

//    UserWorkArea(JPanel userProcess, PetDirectory petDirectory, UserDirectory userDirectory, User user, DoctorList doclist, AdoptionList adl) {
//        initComponents();
//        this.userProcess = userProcess;
//        this.petDirectory = petDirectory;
//        this.userDirectory = userDirectory;
//        this.doclist = doclist;
//        this.user = user;
//        this.adl = adl;
//    }
//    public UserWorkArea(JPanel userProcess, PetDirectory petDirectory, User user, AdoptionList adl) {
//        initComponents();
//        this.userProcess = userProcess;
//        this.petDirectory = petDirectory;
////        this.userDirectory = userDirectory;
////        this.doclist = doclist;
//        this.user = user;
//        this.adl = adl;
//    }
    public UserWorkArea(JPanel userprocess, OnlineStore os, User user) {

        initComponents();
        this.userProcess = userprocess;
        this.os = os;
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewPet = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnPetCAre = new javax.swing.JButton();
        BtnHealthCare = new javax.swing.JButton();
        Adoption = new javax.swing.JButton();
        mypets = new javax.swing.JButton();
        regmypet = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(123, 69, 12));

        ViewPet.setBackground(new java.awt.Color(213, 198, 174));
        ViewPet.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        ViewPet.setText("Shop Pet");
        ViewPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPetActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(213, 198, 174));
        jButton1.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        jButton1.setText("Merch");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnPetCAre.setBackground(new java.awt.Color(213, 198, 174));
        btnPetCAre.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        btnPetCAre.setText("PetCare");
        btnPetCAre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetCAreActionPerformed(evt);
            }
        });

        BtnHealthCare.setBackground(new java.awt.Color(213, 198, 174));
        BtnHealthCare.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        BtnHealthCare.setText("HealthCare");
        BtnHealthCare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHealthCareActionPerformed(evt);
            }
        });

        Adoption.setBackground(new java.awt.Color(213, 198, 174));
        Adoption.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        Adoption.setText("Adoption");
        Adoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdoptionActionPerformed(evt);
            }
        });

        mypets.setBackground(new java.awt.Color(213, 198, 174));
        mypets.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        mypets.setText("My Pets");
        mypets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mypetsActionPerformed(evt);
            }
        });

        regmypet.setBackground(new java.awt.Color(213, 198, 174));
        regmypet.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        regmypet.setText("Register  your Pet");
        regmypet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regmypetActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/moukthikamanapati/Desktop/WhatsApp Image 2022-05-01 at 4.05.28 AM.jpeg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(ViewPet, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(Adoption, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(btnPetCAre, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(BtnHealthCare, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mypets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(regmypet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155)
                        .addComponent(mypets, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(regmypet, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ViewPet, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Adoption, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnHealthCare, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPetCAre, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(240, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPetActionPerformed
//        ViewPet vw = new ViewPet(userProcess, petDirectory, currentorder, clothingDirectory, pricingDirectory, userDirectory, user,doclist,apphis,adl);
        ViewPet vw = new ViewPet(userProcess, os, user);
        userProcess.add("ViewPet", vw);
        CardLayout layout = (CardLayout) userProcess.getLayout();
        layout.next(userProcess);
    }//GEN-LAST:event_ViewPetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Merch mw = new Merch(userProcess, petDirectory, currentorder,clothingDirectory,foodList,medList,merchList);
        Merch mw = new Merch(userProcess, os, user);
        userProcess.add("Merch", mw);
        CardLayout layout = (CardLayout) userProcess.getLayout();
        layout.next(userProcess);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPetCAreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetCAreActionPerformed
        // PetCareServices pc = new PetCareServices(userProcess, petDirectory, pricingDirectory, user,papp);
        PetCareServices pc = new PetCareServices(userProcess, os, user);
        userProcess.add("PetCareServices", pc);
        CardLayout layout = (CardLayout) userProcess.getLayout();
        layout.next(userProcess);
    }//GEN-LAST:event_btnPetCAreActionPerformed

    private void BtnHealthCareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHealthCareActionPerformed
//        Appointment app = new Appointment(userProcess,user,doclist,apphis);
        Appointment app = new Appointment(userProcess, os, user);
        userProcess.add("Appointment", app);
        CardLayout layout = (CardLayout) userProcess.getLayout();
        layout.next(userProcess);
    }//GEN-LAST:event_BtnHealthCareActionPerformed

    private void regmypetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regmypetActionPerformed
        //RegisterMyPet rmp = new RegisterMyPet(userProcess,petDirectory, currentorder,  clothingDirectory,pricingDirectory,userDirectory,  user,doclist,  apphis, adl,foodList,medList,merchList,papp);
///      System.out.print("username test"  + user.getUsername());
        RegisterMyPet rmp = new RegisterMyPet(userProcess, os, user);
        userProcess.add("RegisterMyPet", rmp);
        CardLayout layout = (CardLayout) userProcess.getLayout();
        layout.next(userProcess);

    }//GEN-LAST:event_regmypetActionPerformed

    private void mypetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mypetsActionPerformed
        //MyPet mp = new MyPet(userProcess, petDirectory, userDirectory, user, doclist, adl);
        MyPet mp = new MyPet(userProcess, os, user);
        userProcess.add("MyPet", mp);
        CardLayout layout = (CardLayout) userProcess.getLayout();
        layout.next(userProcess);
    }//GEN-LAST:event_mypetsActionPerformed

    private void AdoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdoptionActionPerformed
        //    AdoptionWorkArea add = new AdoptionWorkArea(userProcess, petDirectory,  user,  adl );
        AdoptionWorkArea add = new AdoptionWorkArea(userProcess, os, user);
        userProcess.add("AdoptionWorkArea", add);
        CardLayout layout = (CardLayout) userProcess.getLayout();
        layout.next(userProcess);
    }//GEN-LAST:event_AdoptionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        new MainJFrame(os).setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adoption;
    private javax.swing.JButton BtnHealthCare;
    private javax.swing.JButton ViewPet;
    private javax.swing.JButton btnPetCAre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mypets;
    private javax.swing.JButton regmypet;
    // End of variables declaration//GEN-END:variables
}
