/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Admin;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import onlinepetstore.OnlineStore;
import onlinepetstore.Pet;
import onlinepetstore.User;
import onlinepetstore.UserDirectory;

/**
 *
 * @author moukthikamanapati
 */
public class UsersDirectory extends javax.swing.JPanel {

    /**
     * Creates new form UsersDirectory
     */
    public UsersDirectory() {
        initComponents();
    }
JPanel userprocess;
OnlineStore os;
UserDirectory userD;
    UsersDirectory(JPanel userprocess, OnlineStore os) {
       initComponents();
       this.userprocess = userprocess;
               this.os = os;
               this.userD = os.getUserDirectory();
    table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        user = new javax.swing.JTable();
        del = new javax.swing.JButton();
        bck = new javax.swing.JButton();

        setBackground(new java.awt.Color(123, 69, 12));

        user.setBackground(new java.awt.Color(219, 210, 196));
        user.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "username", "password", "email"
            }
        ));
        user.setRowHeight(24);
        jScrollPane1.setViewportView(user);

        del.setBackground(new java.awt.Color(255, 255, 204));
        del.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        del.setText("Delete");
        del.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bck.setBackground(new java.awt.Color(255, 255, 204));
        bck.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        bck.setText("BACK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(686, 686, 686)
                        .addComponent(bck, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(bck, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(del, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bck;
    private javax.swing.JButton del;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable user;
    // End of variables declaration//GEN-END:variables

    private void table() {
       DefaultTableModel model = (DefaultTableModel) user.getModel();
        model.setRowCount(0);
        System.out.println("populate on Buy pet  table");
        //  System.out.println(p.getHouse().getCommunity().getCity().getCityName());
        for (User p : userD.getUserList()) {
           //if (p.getCategory().equalsIgnoreCase(pettype)&!(p.getPetType().equalsIgnoreCase("Adoption"))) {
                Object row[] = new Object[3];
                row[0] = p;
                row[1] = p.getPassword();
                row[2] = p.getEmail();
                
                model.addRow(row);
           // }
        } }
}
