/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PersonUI;


import healthcare.CityList;
import healthcare.PatientDirectory;
import healthcare.PersonDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author moukthikamanapati
 */
public class PersonWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form PersonWorkArea
     */
    JPanel userProcessContainer;
    PersonDirectory personDirectory;
    CityList cityList;
    PatientDirectory patientDirectory;
    public PersonWorkArea(JPanel userProcessContainer, PersonDirectory personDirectory,CityList cityList,PatientDirectory patientDirectory) {
         initComponents();
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
        this.cityList = cityList;
        this.patientDirectory = patientDirectory;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnCreatePerson = new javax.swing.JButton();
        BtnViewPerson = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        BtnCreatePerson.setText("Create");
        BtnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreatePersonActionPerformed(evt);
            }
        });

        BtnViewPerson.setText("View");
        BtnViewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewPersonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 0, 18)); // NOI18N
        jLabel1.setText("Person Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(BtnCreatePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(BtnViewPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(346, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCreatePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnViewPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(271, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreatePersonActionPerformed
        //Create person
        PersonCreate pcreate = new PersonCreate(userProcessContainer, personDirectory, cityList);
        userProcessContainer.add("PersonCreate", pcreate);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_BtnCreatePersonActionPerformed

    private void BtnViewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewPersonActionPerformed
        // view person
         PersonView pview = new PersonView(userProcessContainer, personDirectory, patientDirectory);
        userProcessContainer.add("PersonView", pview);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_BtnViewPersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCreatePerson;
    private javax.swing.JButton BtnViewPerson;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
