/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package veternary;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import onlinepetstore.AppointmentDirectory;
import onlinepetstore.DoctorList;
import onlinepetstore.OnlineStore;
import onlinepetstore.Pet;
import onlinepetstore.User;

/**
 *
 * @author moukthikamanapati
 */
public class ViewAppointment extends javax.swing.JPanel {

    private OnlineStore os;

    /**
     * Creates new form ViewAppointment
     */
    public ViewAppointment() {
        initComponents();
    }
    JPanel userProcess;
    User user;
    DoctorList doclist;
    AppointmentDirectory apphis;

    ViewAppointment(JPanel userProcess, User user, DoctorList doclist, AppointmentDirectory apphis) {
        initComponents();
        initComponents();
        this.userProcess = userProcess;
        this.user = user;
        this.doclist = doclist;
        this.apphis = apphis;
        populateTable();
    }

    ViewAppointment(JPanel userProcess, OnlineStore os, User user) {
        initComponents();
        this.userProcess = userProcess;
        this.os = os ;
        this.user = user;
        apphis = os.getApphis();
//         for(onlinepetstore.Appointment app :os.getApphis().getAppointmentList() )
//                {
//        System.out.println("view+" + app.getPet().getPetName());
//        }
        // System.out.println("user in view"+user.getUsername());
        doclist = os.getDoclist();
         apphis = os.getApphis();
        populateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        app = new javax.swing.JTable();
        cancel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(123, 69, 12));

        app.setBackground(new java.awt.Color(219, 210, 196));
        app.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Docname", "Petname"
            }
        ));
        app.setRowHeight(24);
        jScrollPane1.setViewportView(app);

        cancel.setBackground(new java.awt.Color(255, 255, 204));
        cancel.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(765, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        int row = app.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        onlinepetstore.Appointment p = (onlinepetstore.Appointment) app.getValueAt(row, 0);
        apphis.removeAppointment(p);
        populateTable();
    }//GEN-LAST:event_cancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         os.setApphis(apphis);
        for(onlinepetstore.Appointment app :os.getApphis().getAppointmentList() )
                {
        System.out.println("appom+" + app.getUser().getUsername());
        }
       BookAppointment bapp = new BookAppointment(userProcess,os,user);
        userProcess.add("BookAppointment", bapp);
        CardLayout layout = (CardLayout) userProcess.getLayout();
        layout.next(userProcess);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable app;
    private javax.swing.JButton cancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) app.getModel();
        model.setRowCount(0);
        System.out.println("populate on appointment ");

        for (onlinepetstore.Appointment app : apphis.getAppointmentList()) {
        if(app.getUser().getUsername().equals(user.getUsername())){
            Object row[] = new Object[3];
            row[0] = app;

            row[1] = app.getDoc().getDoctorName();
            row[2] = app.getPet().getPetName();
            model.addRow(row);
        }
        }
    }
}
